name: Update data

on:
  schedule:
    # 1日1回 https://zenn.dev/rie_amasato/articles/f901ef9fb19415
    - cron: "40 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -r requirements.txt
      - run: ls public_data
      - run: python main.py
      - run: ls public_data
      - run: sed -i '/^public_data$/d' .gitignore
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Bot] auto update"
          file_pattern: public_data/*.json
          branch: publish
          create_branch: true
          push_options: '--force'
